Added the get current location
yogeshktm/illumination-chrome-extension pull request #1
Opened 2018-12-01 12:21 UTC by Vimalraj578

Added the Location Based weather

2018-12-03 08:28 UTC, yogeshktm commented on js/app.js
> +                return fetch('https://www.metaweather.com/api/location/' + data[0]['woeid']);
@Vimalraj578

Why it fetches always data[0]. you got woeid of current location. then it should fetch data based on that right ? Means it will show chennai's weather in banglaore. isn't it ?

2018-12-03 08:40 UTC, yogeshktm requested changes
@Vimalraj578 

- [ ] Try figuring out the logic to fetch dynamic data of current location not data[0]. 
- [ ] Print the current city above weather info. so you can aware of the current city.

2018-12-03 13:25 UTC, Vimalraj571 commented on js/app.js
> +                return fetch('https://www.metaweather.com/api/location/' + data[0]['woeid']);
On first FETCH it only gives the Array of Location Based on the Lat and lat (possibly nearby)values 
`fetch('https://www.metaweather.com/api/location/search/?lattlong=' + latitude + ',' + longitude)`
On the first array with the Key 0 (data[0]['woeid']) represent the very nearby location's woeid.So I used that Data[0] with key....!

2018-12-03 13:55 UTC, yogeshktm commented on js/app.js
> +                return fetch('https://www.metaweather.com/api/location/' + data[0]['woeid']);
Is there is any way to match or search the rounded values of lat and long in that array and display the data in that array index. if not try this [Open weather API](https://openweathermap.org/api) .

2018-12-03 14:07 UTC, Vimalraj578 commented on js/app.js
> +                return fetch('https://www.metaweather.com/api/location/' + data[0]['woeid']);
Did get it...!

2018-12-04 06:33 UTC, yogeshktm approved these changes
Merged PR for local weather change and display city name

2018-12-04 07:42 UTC, merged